//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 01:24:11 PM CEST 
//


package smestaj;

import xmlProjectSpringbootstarter.tipsmestaja.Tipsmestaja;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tip" type="{smestaj}tip_smestaja" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tip"
})
@XmlRootElement(name = "getTipoviResponse")
public class GetTipoviResponse {

    @XmlElement(required = true)
    protected List<Tipsmestaja> tip;

    /**
     * Gets the value of the tip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipSmestaja }
     * 
     * 
     */
    public List<Tipsmestaja> getTip() {
        if (tip == null) {
            tip = new ArrayList<Tipsmestaja>();
        }
        return this.tip;
    }

    public void setTip(List<Tipsmestaja> tip) {
        this.tip = tip;
    }
}
