//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 01:24:11 PM CEST 
//


package smestaj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the smestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: smestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddSmestajRequest }
     * 
     */
    public AddSmestajRequest createAddSmestajRequest() {
        return new AddSmestajRequest();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link GetDodatneUslugeRequest }
     * 
     */
    public GetDodatneUslugeRequest createGetDodatneUslugeRequest() {
        return new GetDodatneUslugeRequest();
    }

    /**
     * Create an instance of {@link GetKategorijeResponse }
     * 
     */
    public GetKategorijeResponse createGetKategorijeResponse() {
        return new GetKategorijeResponse();
    }

    /**
     * Create an instance of {@link Kategorija }
     * 
     */
    public Kategorija createKategorija() {
        return new Kategorija();
    }

    /**
     * Create an instance of {@link GetKategorijeRequest }
     * 
     */
    public GetKategorijeRequest createGetKategorijeRequest() {
        return new GetKategorijeRequest();
    }

    /**
     * Create an instance of {@link AddZauzetostRequest }
     * 
     */
    public AddZauzetostRequest createAddZauzetostRequest() {
        return new AddZauzetostRequest();
    }

    /**
     * Create an instance of {@link Zauzetost }
     * 
     */
    public Zauzetost createZauzetost() {
        return new Zauzetost();
    }

    /**
     * Create an instance of {@link AddZauzetostResponse }
     * 
     */
    public AddZauzetostResponse createAddZauzetostResponse() {
        return new AddZauzetostResponse();
    }

    /**
     * Create an instance of {@link GetCoountryRequest }
     * 
     */
    public GetCoountryRequest createGetCoountryRequest() {
        return new GetCoountryRequest();
    }

    /**
     * Create an instance of {@link GetDodatneUslugeResponse }
     * 
     */
    public GetDodatneUslugeResponse createGetDodatneUslugeResponse() {
        return new GetDodatneUslugeResponse();
    }

    /**
     * Create an instance of {@link DodatnaUsluga }
     * 
     */
    public DodatnaUsluga createDodatnaUsluga() {
        return new DodatnaUsluga();
    }

    /**
     * Create an instance of {@link AddSmestajResponse }
     * 
     */
    public AddSmestajResponse createAddSmestajResponse() {
        return new AddSmestajResponse();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link Drzava }
     * 
     */
    public Drzava createDrzava() {
        return new Drzava();
    }

    /**
     * Create an instance of {@link GetTipoviRequest }
     * 
     */
    public GetTipoviRequest createGetTipoviRequest() {
        return new GetTipoviRequest();
    }

    /**
     * Create an instance of {@link GetTipoviResponse }
     * 
     */
    public GetTipoviResponse createGetTipoviResponse() {
        return new GetTipoviResponse();
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link Posetilac }
     * 
     */
    public Posetilac createPosetilac() {
        return new Posetilac();
    }

    /**
     * Create an instance of {@link Termin }
     * 
     */
    public Termin createTermin() {
        return new Termin();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link Lice }
     * 
     */
    public Lice createLice() {
        return new Lice();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link NaseljenoMesto }
     * 
     */
    public NaseljenoMesto createNaseljenoMesto() {
        return new NaseljenoMesto();
    }

    /**
     * Create an instance of {@link Radnik }
     * 
     */
    public Radnik createRadnik() {
        return new Radnik();
    }

}
