//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.09 at 05:38:03 PM CEST 
//


package smestaj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the smestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: smestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link Drzava }
     * 
     */
    public Drzava createDrzava() {
        return new Drzava();
    }

    /**
     * Create an instance of {@link NaseljenoMesto }
     * 
     */
    public NaseljenoMesto createNaseljenoMesto() {
        return new NaseljenoMesto();
    }

    /**
     * Create an instance of {@link Lice }
     * 
     */
    public Lice createLice() {
        return new Lice();
    }

    /**
     * Create an instance of {@link Posetilac }
     * 
     */
    public Posetilac createPosetilac() {
        return new Posetilac();
    }

    /**
     * Create an instance of {@link Radnik }
     * 
     */
    public Radnik createRadnik() {
        return new Radnik();
    }

    /**
     * Create an instance of {@link Termin }
     * 
     */
    public Termin createTermin() {
        return new Termin();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

}
