//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_Agent.SmestajSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="smestaj", ConfigurationName="SmestajSOAP.SmestajServicePort", CallbackContract=typeof(XML_Agent.SmestajSOAP.SmestajServicePortCallback))]
    public interface SmestajServicePort {
        
        // CODEGEN: Generating message contract since the operation addZauzetost is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.addZauzetostResponse1 addZauzetost(XML_Agent.SmestajSOAP.addZauzetostRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addZauzetostResponse1> addZauzetostAsync(XML_Agent.SmestajSOAP.addZauzetostRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getDodatneUsluge is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.getDodatneUslugeResponse getDodatneUsluge(XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getDodatneUslugeResponse> getDodatneUslugeAsync(XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getTipovi is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.getTipoviResponse getTipovi(XML_Agent.SmestajSOAP.getTipoviRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getTipoviResponse> getTipoviAsync(XML_Agent.SmestajSOAP.getTipoviRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAgent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.getAgentResponse1 getAgent(XML_Agent.SmestajSOAP.getAgentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getAgentResponse1> getAgentAsync(XML_Agent.SmestajSOAP.getAgentRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getKategorije is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.getKategorijeResponse getKategorije(XML_Agent.SmestajSOAP.getKategorijeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getKategorijeResponse> getKategorijeAsync(XML_Agent.SmestajSOAP.getKategorijeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addSmestaj is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        XML_Agent.SmestajSOAP.addSmestajResponse1 addSmestaj(XML_Agent.SmestajSOAP.addSmestajRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addSmestajResponse1> addSmestajAsync(XML_Agent.SmestajSOAP.addSmestajRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getCoountry is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        void getCoountry(XML_Agent.SmestajSOAP.getCoountryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task getCoountryAsync(XML_Agent.SmestajSOAP.getCoountryRequest1 request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmestajServicePortCallback {
        
        // CODEGEN: Generating message contract since the operation getCountry is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lice))]
        void getCountry(XML_Agent.SmestajSOAP.getCountryResponse1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class addZauzetostRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private zauzetost zauzetostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public zauzetost zauzetost {
            get {
                return this.zauzetostField;
            }
            set {
                this.zauzetostField = value;
                this.RaisePropertyChanged("zauzetost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class zauzetost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datum_pocetkaField;
        
        private System.DateTime datum_krajaField;
        
        private string idSmestajaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime datum_pocetka {
            get {
                return this.datum_pocetkaField;
            }
            set {
                this.datum_pocetkaField = value;
                this.RaisePropertyChanged("datum_pocetka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime datum_kraja {
            get {
                return this.datum_krajaField;
            }
            set {
                this.datum_krajaField = value;
                this.RaisePropertyChanged("datum_kraja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string idSmestaja {
            get {
                return this.idSmestajaField;
            }
            set {
                this.idSmestajaField = value;
                this.RaisePropertyChanged("idSmestaja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class termin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private int mesecField;
        
        private int cenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int mesec {
            get {
                return this.mesecField;
            }
            set {
                this.mesecField = value;
                this.RaisePropertyChanged("mesec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
                this.RaisePropertyChanged("cena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class komentar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string imeField;
        
        private string sadrzajField;
        
        private bool odobrenField;
        
        private string idSmestajaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
                this.RaisePropertyChanged("ime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sadrzaj {
            get {
                return this.sadrzajField;
            }
            set {
                this.sadrzajField = value;
                this.RaisePropertyChanged("sadrzaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool odobren {
            get {
                return this.odobrenField;
            }
            set {
                this.odobrenField = value;
                this.RaisePropertyChanged("odobren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idSmestaja {
            get {
                return this.idSmestajaField;
            }
            set {
                this.idSmestajaField = value;
                this.RaisePropertyChanged("idSmestaja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class drzava : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        private string sifraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sifra {
            get {
                return this.sifraField;
            }
            set {
                this.sifraField = value;
                this.RaisePropertyChanged("sifra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class naseljeno_mesto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        private string pttBrojField;
        
        private drzava drzavaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pttBroj {
            get {
                return this.pttBrojField;
            }
            set {
                this.pttBrojField = value;
                this.RaisePropertyChanged("pttBroj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public drzava drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
                this.RaisePropertyChanged("drzava");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class smestaj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        private int kapacitetField;
        
        private naseljeno_mesto naseljeno_mestoField;
        
        private string opisField;
        
        private string[] slikeField;
        
        private rezervacija[] rezervacijeField;
        
        private zauzetost[] zauzetoField;
        
        private komentar[] komentariField;
        
        private radnik agentField;
        
        private tip_smestaja tip_smestajaField;
        
        private kategorija kategorija_smestajaField;
        
        private termin[] terminiField;
        
        private dodatna_usluga[] dodtane_uslugeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int kapacitet {
            get {
                return this.kapacitetField;
            }
            set {
                this.kapacitetField = value;
                this.RaisePropertyChanged("kapacitet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public naseljeno_mesto naseljeno_mesto {
            get {
                return this.naseljeno_mestoField;
            }
            set {
                this.naseljeno_mestoField = value;
                this.RaisePropertyChanged("naseljeno_mesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
                this.RaisePropertyChanged("opis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("slike", Order=5)]
        public string[] slike {
            get {
                return this.slikeField;
            }
            set {
                this.slikeField = value;
                this.RaisePropertyChanged("slike");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rezervacije", Order=6)]
        public rezervacija[] rezervacije {
            get {
                return this.rezervacijeField;
            }
            set {
                this.rezervacijeField = value;
                this.RaisePropertyChanged("rezervacije");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zauzeto", Order=7)]
        public zauzetost[] zauzeto {
            get {
                return this.zauzetoField;
            }
            set {
                this.zauzetoField = value;
                this.RaisePropertyChanged("zauzeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("komentari", Order=8)]
        public komentar[] komentari {
            get {
                return this.komentariField;
            }
            set {
                this.komentariField = value;
                this.RaisePropertyChanged("komentari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public radnik agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
                this.RaisePropertyChanged("agent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public tip_smestaja tip_smestaja {
            get {
                return this.tip_smestajaField;
            }
            set {
                this.tip_smestajaField = value;
                this.RaisePropertyChanged("tip_smestaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public kategorija kategorija_smestaja {
            get {
                return this.kategorija_smestajaField;
            }
            set {
                this.kategorija_smestajaField = value;
                this.RaisePropertyChanged("kategorija_smestaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("termini", Order=12)]
        public termin[] termini {
            get {
                return this.terminiField;
            }
            set {
                this.terminiField = value;
                this.RaisePropertyChanged("termini");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dodtane_usluge", Order=13)]
        public dodatna_usluga[] dodtane_usluge {
            get {
                return this.dodtane_uslugeField;
            }
            set {
                this.dodtane_uslugeField = value;
                this.RaisePropertyChanged("dodtane_usluge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class rezervacija : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private System.DateTime datum_dolaskaField;
        
        private System.DateTime datum_odlaskaField;
        
        private string naziv_smestajaField;
        
        private string id_smestajaField;
        
        private string id_korisnikaField;
        
        private radnik agentField;
        
        private bool izvrsenoField;
        
        private int cenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime datum_dolaska {
            get {
                return this.datum_dolaskaField;
            }
            set {
                this.datum_dolaskaField = value;
                this.RaisePropertyChanged("datum_dolaska");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime datum_odlaska {
            get {
                return this.datum_odlaskaField;
            }
            set {
                this.datum_odlaskaField = value;
                this.RaisePropertyChanged("datum_odlaska");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string naziv_smestaja {
            get {
                return this.naziv_smestajaField;
            }
            set {
                this.naziv_smestajaField = value;
                this.RaisePropertyChanged("naziv_smestaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string id_smestaja {
            get {
                return this.id_smestajaField;
            }
            set {
                this.id_smestajaField = value;
                this.RaisePropertyChanged("id_smestaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string id_korisnika {
            get {
                return this.id_korisnikaField;
            }
            set {
                this.id_korisnikaField = value;
                this.RaisePropertyChanged("id_korisnika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public radnik agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
                this.RaisePropertyChanged("agent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool izvrseno {
            get {
                return this.izvrsenoField;
            }
            set {
                this.izvrsenoField = value;
                this.RaisePropertyChanged("izvrseno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
                this.RaisePropertyChanged("cena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class radnik : lice {
        
        private string pmbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string pmb {
            get {
                return this.pmbField;
            }
            set {
                this.pmbField = value;
                this.RaisePropertyChanged("pmb");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(posetilac))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(radnik))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class lice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string imeField;
        
        private string prezimeField;
        
        private string[] broj_telefonaField;
        
        private string emailField;
        
        private string passwordField;
        
        private string adresaField;
        
        private rezervacija[] rezervacijeField;
        
        private poruka[] primljene_porukeField;
        
        private poruka[] poslate_porukeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
                this.RaisePropertyChanged("ime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string prezime {
            get {
                return this.prezimeField;
            }
            set {
                this.prezimeField = value;
                this.RaisePropertyChanged("prezime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("broj_telefona", Order=3)]
        public string[] broj_telefona {
            get {
                return this.broj_telefonaField;
            }
            set {
                this.broj_telefonaField = value;
                this.RaisePropertyChanged("broj_telefona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string adresa {
            get {
                return this.adresaField;
            }
            set {
                this.adresaField = value;
                this.RaisePropertyChanged("adresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rezervacije", Order=7)]
        public rezervacija[] rezervacije {
            get {
                return this.rezervacijeField;
            }
            set {
                this.rezervacijeField = value;
                this.RaisePropertyChanged("rezervacije");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primljene_poruke", Order=8)]
        public poruka[] primljene_poruke {
            get {
                return this.primljene_porukeField;
            }
            set {
                this.primljene_porukeField = value;
                this.RaisePropertyChanged("primljene_poruke");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("poslate_poruke", Order=9)]
        public poruka[] poslate_poruke {
            get {
                return this.poslate_porukeField;
            }
            set {
                this.poslate_porukeField = value;
                this.RaisePropertyChanged("poslate_poruke");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class poruka : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string sadrzajField;
        
        private string posaljilacField;
        
        private string primalacField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sadrzaj {
            get {
                return this.sadrzajField;
            }
            set {
                this.sadrzajField = value;
                this.RaisePropertyChanged("sadrzaj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string posaljilac {
            get {
                return this.posaljilacField;
            }
            set {
                this.posaljilacField = value;
                this.RaisePropertyChanged("posaljilac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string primalac {
            get {
                return this.primalacField;
            }
            set {
                this.primalacField = value;
                this.RaisePropertyChanged("primalac");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class posetilac : lice {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class tip_smestaja : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class kategorija : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="smestaj")]
    public partial class dodatna_usluga : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
                this.RaisePropertyChanged("naziv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class addZauzetostResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addZauzetostRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.addZauzetostRequest addZauzetostRequest;
        
        public addZauzetostRequest1() {
        }
        
        public addZauzetostRequest1(XML_Agent.SmestajSOAP.addZauzetostRequest addZauzetostRequest) {
            this.addZauzetostRequest = addZauzetostRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addZauzetostResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.addZauzetostResponse addZauzetostResponse;
        
        public addZauzetostResponse1() {
        }
        
        public addZauzetostResponse1(XML_Agent.SmestajSOAP.addZauzetostResponse addZauzetostResponse) {
            this.addZauzetostResponse = addZauzetostResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getDodatneUslugeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDodatneUslugeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getDodatneUslugeRequest getDodatneUslugeRequest;
        
        public getDodatneUslugeRequest1() {
        }
        
        public getDodatneUslugeRequest1(XML_Agent.SmestajSOAP.getDodatneUslugeRequest getDodatneUslugeRequest) {
            this.getDodatneUslugeRequest = getDodatneUslugeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDodatneUslugeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDodatneUslugeResponse", Namespace="smestaj", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public XML_Agent.SmestajSOAP.dodatna_usluga[] getDodatneUslugeResponse1;
        
        public getDodatneUslugeResponse() {
        }
        
        public getDodatneUslugeResponse(XML_Agent.SmestajSOAP.dodatna_usluga[] getDodatneUslugeResponse1) {
            this.getDodatneUslugeResponse1 = getDodatneUslugeResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getTipoviRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoviRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getTipoviRequest getTipoviRequest;
        
        public getTipoviRequest1() {
        }
        
        public getTipoviRequest1(XML_Agent.SmestajSOAP.getTipoviRequest getTipoviRequest) {
            this.getTipoviRequest = getTipoviRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoviResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTipoviResponse", Namespace="smestaj", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tip", IsNullable=false)]
        public XML_Agent.SmestajSOAP.tip_smestaja[] getTipoviResponse1;
        
        public getTipoviResponse() {
        }
        
        public getTipoviResponse(XML_Agent.SmestajSOAP.tip_smestaja[] getTipoviResponse1) {
            this.getTipoviResponse1 = getTipoviResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getAgentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getAgentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private radnik agentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public radnik agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
                this.RaisePropertyChanged("agent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAgentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getAgentRequest getAgentRequest;
        
        public getAgentRequest1() {
        }
        
        public getAgentRequest1(XML_Agent.SmestajSOAP.getAgentRequest getAgentRequest) {
            this.getAgentRequest = getAgentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAgentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getAgentResponse getAgentResponse;
        
        public getAgentResponse1() {
        }
        
        public getAgentResponse1(XML_Agent.SmestajSOAP.getAgentResponse getAgentResponse) {
            this.getAgentResponse = getAgentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getKategorijeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKategorijeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getKategorijeRequest getKategorijeRequest;
        
        public getKategorijeRequest1() {
        }
        
        public getKategorijeRequest1(XML_Agent.SmestajSOAP.getKategorijeRequest getKategorijeRequest) {
            this.getKategorijeRequest = getKategorijeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKategorijeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKategorijeResponse", Namespace="smestaj", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public XML_Agent.SmestajSOAP.kategorija[] getKategorijeResponse1;
        
        public getKategorijeResponse() {
        }
        
        public getKategorijeResponse(XML_Agent.SmestajSOAP.kategorija[] getKategorijeResponse1) {
            this.getKategorijeResponse1 = getKategorijeResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class addSmestajRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private smestaj smestajField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public smestaj smestaj {
            get {
                return this.smestajField;
            }
            set {
                this.smestajField = value;
                this.RaisePropertyChanged("smestaj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class addSmestajResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addSmestajRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.addSmestajRequest addSmestajRequest;
        
        public addSmestajRequest1() {
        }
        
        public addSmestajRequest1(XML_Agent.SmestajSOAP.addSmestajRequest addSmestajRequest) {
            this.addSmestajRequest = addSmestajRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addSmestajResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.addSmestajResponse addSmestajResponse;
        
        public addSmestajResponse1() {
        }
        
        public addSmestajResponse1(XML_Agent.SmestajSOAP.addSmestajResponse addSmestajResponse) {
            this.addSmestajResponse = addSmestajResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getCountryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private drzava drzavaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public drzava drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
                this.RaisePropertyChanged("drzava");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getCountryResponse getCountryResponse;
        
        public getCountryResponse1() {
        }
        
        public getCountryResponse1(XML_Agent.SmestajSOAP.getCountryResponse getCountryResponse) {
            this.getCountryResponse = getCountryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="smestaj")]
    public partial class getCoountryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCoountryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="smestaj", Order=0)]
        public XML_Agent.SmestajSOAP.getCoountryRequest getCoountryRequest;
        
        public getCoountryRequest1() {
        }
        
        public getCoountryRequest1(XML_Agent.SmestajSOAP.getCoountryRequest getCoountryRequest) {
            this.getCoountryRequest = getCoountryRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmestajServicePortChannel : XML_Agent.SmestajSOAP.SmestajServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmestajServicePortClient : System.ServiceModel.DuplexClientBase<XML_Agent.SmestajSOAP.SmestajServicePort>, XML_Agent.SmestajSOAP.SmestajServicePort {
        
        public SmestajServicePortClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SmestajServicePortClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SmestajServicePortClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SmestajServicePortClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SmestajServicePortClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.addZauzetostResponse1 XML_Agent.SmestajSOAP.SmestajServicePort.addZauzetost(XML_Agent.SmestajSOAP.addZauzetostRequest1 request) {
            return base.Channel.addZauzetost(request);
        }
        
        public XML_Agent.SmestajSOAP.addZauzetostResponse addZauzetost(XML_Agent.SmestajSOAP.addZauzetostRequest addZauzetostRequest) {
            XML_Agent.SmestajSOAP.addZauzetostRequest1 inValue = new XML_Agent.SmestajSOAP.addZauzetostRequest1();
            inValue.addZauzetostRequest = addZauzetostRequest;
            XML_Agent.SmestajSOAP.addZauzetostResponse1 retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).addZauzetost(inValue);
            return retVal.addZauzetostResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addZauzetostResponse1> XML_Agent.SmestajSOAP.SmestajServicePort.addZauzetostAsync(XML_Agent.SmestajSOAP.addZauzetostRequest1 request) {
            return base.Channel.addZauzetostAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addZauzetostResponse1> addZauzetostAsync(XML_Agent.SmestajSOAP.addZauzetostRequest addZauzetostRequest) {
            XML_Agent.SmestajSOAP.addZauzetostRequest1 inValue = new XML_Agent.SmestajSOAP.addZauzetostRequest1();
            inValue.addZauzetostRequest = addZauzetostRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).addZauzetostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.getDodatneUslugeResponse XML_Agent.SmestajSOAP.SmestajServicePort.getDodatneUsluge(XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 request) {
            return base.Channel.getDodatneUsluge(request);
        }
        
        public XML_Agent.SmestajSOAP.dodatna_usluga[] getDodatneUsluge(XML_Agent.SmestajSOAP.getDodatneUslugeRequest getDodatneUslugeRequest) {
            XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 inValue = new XML_Agent.SmestajSOAP.getDodatneUslugeRequest1();
            inValue.getDodatneUslugeRequest = getDodatneUslugeRequest;
            XML_Agent.SmestajSOAP.getDodatneUslugeResponse retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getDodatneUsluge(inValue);
            return retVal.getDodatneUslugeResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getDodatneUslugeResponse> XML_Agent.SmestajSOAP.SmestajServicePort.getDodatneUslugeAsync(XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 request) {
            return base.Channel.getDodatneUslugeAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getDodatneUslugeResponse> getDodatneUslugeAsync(XML_Agent.SmestajSOAP.getDodatneUslugeRequest getDodatneUslugeRequest) {
            XML_Agent.SmestajSOAP.getDodatneUslugeRequest1 inValue = new XML_Agent.SmestajSOAP.getDodatneUslugeRequest1();
            inValue.getDodatneUslugeRequest = getDodatneUslugeRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getDodatneUslugeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.getTipoviResponse XML_Agent.SmestajSOAP.SmestajServicePort.getTipovi(XML_Agent.SmestajSOAP.getTipoviRequest1 request) {
            return base.Channel.getTipovi(request);
        }
        
        public XML_Agent.SmestajSOAP.tip_smestaja[] getTipovi(XML_Agent.SmestajSOAP.getTipoviRequest getTipoviRequest) {
            XML_Agent.SmestajSOAP.getTipoviRequest1 inValue = new XML_Agent.SmestajSOAP.getTipoviRequest1();
            inValue.getTipoviRequest = getTipoviRequest;
            XML_Agent.SmestajSOAP.getTipoviResponse retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getTipovi(inValue);
            return retVal.getTipoviResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getTipoviResponse> XML_Agent.SmestajSOAP.SmestajServicePort.getTipoviAsync(XML_Agent.SmestajSOAP.getTipoviRequest1 request) {
            return base.Channel.getTipoviAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getTipoviResponse> getTipoviAsync(XML_Agent.SmestajSOAP.getTipoviRequest getTipoviRequest) {
            XML_Agent.SmestajSOAP.getTipoviRequest1 inValue = new XML_Agent.SmestajSOAP.getTipoviRequest1();
            inValue.getTipoviRequest = getTipoviRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getTipoviAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.getAgentResponse1 XML_Agent.SmestajSOAP.SmestajServicePort.getAgent(XML_Agent.SmestajSOAP.getAgentRequest1 request) {
            return base.Channel.getAgent(request);
        }
        
        public XML_Agent.SmestajSOAP.getAgentResponse getAgent(XML_Agent.SmestajSOAP.getAgentRequest getAgentRequest) {
            XML_Agent.SmestajSOAP.getAgentRequest1 inValue = new XML_Agent.SmestajSOAP.getAgentRequest1();
            inValue.getAgentRequest = getAgentRequest;
            XML_Agent.SmestajSOAP.getAgentResponse1 retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getAgent(inValue);
            return retVal.getAgentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getAgentResponse1> XML_Agent.SmestajSOAP.SmestajServicePort.getAgentAsync(XML_Agent.SmestajSOAP.getAgentRequest1 request) {
            return base.Channel.getAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getAgentResponse1> getAgentAsync(XML_Agent.SmestajSOAP.getAgentRequest getAgentRequest) {
            XML_Agent.SmestajSOAP.getAgentRequest1 inValue = new XML_Agent.SmestajSOAP.getAgentRequest1();
            inValue.getAgentRequest = getAgentRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getAgentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.getKategorijeResponse XML_Agent.SmestajSOAP.SmestajServicePort.getKategorije(XML_Agent.SmestajSOAP.getKategorijeRequest1 request) {
            return base.Channel.getKategorije(request);
        }
        
        public XML_Agent.SmestajSOAP.kategorija[] getKategorije(XML_Agent.SmestajSOAP.getKategorijeRequest getKategorijeRequest) {
            XML_Agent.SmestajSOAP.getKategorijeRequest1 inValue = new XML_Agent.SmestajSOAP.getKategorijeRequest1();
            inValue.getKategorijeRequest = getKategorijeRequest;
            XML_Agent.SmestajSOAP.getKategorijeResponse retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getKategorije(inValue);
            return retVal.getKategorijeResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getKategorijeResponse> XML_Agent.SmestajSOAP.SmestajServicePort.getKategorijeAsync(XML_Agent.SmestajSOAP.getKategorijeRequest1 request) {
            return base.Channel.getKategorijeAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.getKategorijeResponse> getKategorijeAsync(XML_Agent.SmestajSOAP.getKategorijeRequest getKategorijeRequest) {
            XML_Agent.SmestajSOAP.getKategorijeRequest1 inValue = new XML_Agent.SmestajSOAP.getKategorijeRequest1();
            inValue.getKategorijeRequest = getKategorijeRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getKategorijeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_Agent.SmestajSOAP.addSmestajResponse1 XML_Agent.SmestajSOAP.SmestajServicePort.addSmestaj(XML_Agent.SmestajSOAP.addSmestajRequest1 request) {
            return base.Channel.addSmestaj(request);
        }
        
        public XML_Agent.SmestajSOAP.addSmestajResponse addSmestaj(XML_Agent.SmestajSOAP.addSmestajRequest addSmestajRequest) {
            XML_Agent.SmestajSOAP.addSmestajRequest1 inValue = new XML_Agent.SmestajSOAP.addSmestajRequest1();
            inValue.addSmestajRequest = addSmestajRequest;
            XML_Agent.SmestajSOAP.addSmestajResponse1 retVal = ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).addSmestaj(inValue);
            return retVal.addSmestajResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addSmestajResponse1> XML_Agent.SmestajSOAP.SmestajServicePort.addSmestajAsync(XML_Agent.SmestajSOAP.addSmestajRequest1 request) {
            return base.Channel.addSmestajAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_Agent.SmestajSOAP.addSmestajResponse1> addSmestajAsync(XML_Agent.SmestajSOAP.addSmestajRequest addSmestajRequest) {
            XML_Agent.SmestajSOAP.addSmestajRequest1 inValue = new XML_Agent.SmestajSOAP.addSmestajRequest1();
            inValue.addSmestajRequest = addSmestajRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).addSmestajAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void XML_Agent.SmestajSOAP.SmestajServicePort.getCoountry(XML_Agent.SmestajSOAP.getCoountryRequest1 request) {
            base.Channel.getCoountry(request);
        }
        
        public void getCoountry(XML_Agent.SmestajSOAP.getCoountryRequest getCoountryRequest) {
            XML_Agent.SmestajSOAP.getCoountryRequest1 inValue = new XML_Agent.SmestajSOAP.getCoountryRequest1();
            inValue.getCoountryRequest = getCoountryRequest;
            ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getCoountry(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task XML_Agent.SmestajSOAP.SmestajServicePort.getCoountryAsync(XML_Agent.SmestajSOAP.getCoountryRequest1 request) {
            return base.Channel.getCoountryAsync(request);
        }
        
        public System.Threading.Tasks.Task getCoountryAsync(XML_Agent.SmestajSOAP.getCoountryRequest getCoountryRequest) {
            XML_Agent.SmestajSOAP.getCoountryRequest1 inValue = new XML_Agent.SmestajSOAP.getCoountryRequest1();
            inValue.getCoountryRequest = getCoountryRequest;
            return ((XML_Agent.SmestajSOAP.SmestajServicePort)(this)).getCoountryAsync(inValue);
        }
    }
}
